# Generated by Django 4.1.1 on 2022-09-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('owner_id', models.PositiveIntegerField(verbose_name='owner id')),
                ('owner_name', models.CharField(max_length=30, verbose_name='owner name')),
                ('thumb_url', models.URLField(blank=True, null=True, verbose_name='thumb url')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='cover url')),
                ('description', models.TextField(verbose_name='description')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='total score')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='total tasks')),
                ('unchangeable', models.BooleanField(verbose_name='unchangeable')),
                ('include_weekly_report', models.BooleanField(verbose_name='include weekly report')),
                ('content_type', models.PositiveIntegerField(verbose_name='content type')),
                ('is_netology', models.BooleanField(verbose_name='is netology')),
                ('bg_url', models.URLField(blank=True, null=True, verbose_name='bg url')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('demo', models.BooleanField(verbose_name='demo')),
                ('custom_author_names', models.CharField(max_length=30, verbose_name='custom author names')),
                ('custom_contents_link', models.URLField(blank=True, null=True, verbose_name='custom contents link')),
                ('hide_viewer_navigation', models.BooleanField(verbose_name='hide viewer navigation')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='courses.course', verbose_name='course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('last_name', models.CharField(max_length=30, verbose_name='name')),
                ('role_id', models.PositiveIntegerField(verbose_name='role')),
                ('auth_type', models.PositiveIntegerField(verbose_name='auth type')),
                ('last_activity_at', models.PositiveIntegerField(blank=True, null=True, verbose_name='last activity at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='courses.course', verbose_name='course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
